use_frameworks!

target 'SmartProxy_Example' do
  pod 'SmartProxy', :path => '../'

  target 'SmartProxy_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  pod 'Alamofire', '~> 4.4.0'
  end
end
