use_frameworks!

target 'SmartProxy_Example' do
	pod 'SmartProxy', :path => '../'

	pod 'SwiftyJSON', '~> 3.0'
	pod 'Alamofire', '~> 4.0'
	
	target 'SmartProxy_Tests' do
		inherit! :search_paths
	end
end
